### ISSUE TITLE
Responsive overlapping

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2020-coming-soon#1]
![Screen Shot 2020-01-22 at 9 17 36 AM](https://user-images.githubusercontent.com/105192/72901686-2f385b80-3cf8-11ea-99cc-705da99f766d.png)
![Screen Shot 2020-01-22 at 9 17 25 AM](https://user-images.githubusercontent.com/105192/72901687-2f385b80-3cf8-11ea-8907-0a3801fcd63a.png)

**Comment by sander-aaron** [comment]
I fixed the issue. I replaced the pin-b since that's what was causing the overlap.
